---
- hosts: clients
  become: true
  tasks:
    - name: Install Python-PIP
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip

    - name: Install Swift and OpenStack Client PIP packages
      pip:
        name: "{{ item }}"
      with_items:
        - python-swiftclient
        - python-openstackclient
